name: bla

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Try to fail
        run: exit 1
      - name: Print message if we don't fail
        run: echo Should not get here

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print message if we don't fail
        run: echo Should not get here