name: bla

on:
  - push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Set a multiline environment variable
        run: |
          echo "EVENT_PATH_JSON<<EOF" >> "$GITHUB_ENV"
          echo $(cat $GITHUB_EVENT_PATH) >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      - name: Print multiline environment variable
        run: |
          echo "${{ fromJSON(env.EVENT_PATH_JSON).after }}...${{ fromJSON(env.EVENT_PATH_JSON).before }}"
  

  bla:
    name: Bla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GITHUB_EVENT_PATH
        run: |
          echo "$GITHUB_EVENT_PATH"
      - run: |
          echo $GITHUB_EVENT_PATH
      - run: |
          echo "${{ env.GITHUB_EVENT_PATH }}"
      - run: |
          echo "${{ fromJSON(env.GITHUB_EVENT_PATH) }}"
