name: bla

on:
  - push

jobs:
  build_commit_range:
    runs-on: ubuntu-latest
    outputs:
      commit_range: ${{steps.create_commit_range.outputs.commit_range}}
    steps:
      - name: Read Github event details
        run: |
          echo "EVENT_PATH_JSON<<EOF" >> "$GITHUB_ENV"
          echo $(cat $GITHUB_EVENT_PATH) >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      - name: Create commit range variable
        id: create_commit_range
        run: |
          echo "commit_range=${{ fromJSON(env.EVENT_PATH_JSON).after }}...${{ fromJSON(env.EVENT_PATH_JSON).before }} >> $GITHUB_OUTPUT"

  use_commit_range:
    needs: build_commit_range
    runs-on: ubuntu-latest
    steps:
      - name: Using commit range variable
        run: |
          echo "${{ needs.build_commit_range.outputs.commit_range }}"
