name: bla

on:
  - push

jobs:
  bla:
    name: Bla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GITHUB_EVENT_PATH
        run: |
          echo "${{ GITHUB_EVENT_PATH.after }}"
