name: bla

on:
  - push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Set a multiline environment variable
        run: |
          echo "LIBRARIES_JSON<<EOF" >> "$GITHUB_ENV"
          echo $(cat ${{ github.event.path }}) >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      - name: Print multiline environment variable
        run: |
          echo "${{ env.LIBRARIES_JSON }}"
  

  bla:
    name: Bla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GITHUB_EVENT_PATH
        run: |
          echo "$GITHUB_EVENT_PATH"
      - run: |
          echo $GITHUB_EVENT_PATH
      - run: |
          echo "${{ env.GITHUB_EVENT_PATH }}"
      - run: |
          echo "${{ fromJSON(env.GITHUB_EVENT_PATH) }}"
