name: bla

on:
  - push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    env:
      RAFAEL_REF: ${{ github.ref }}
    steps:
      - run: echo '$RAFAEL_REF'

  bla:
    name: Bla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print GITHUB_EVENT_PATH
        run: |
          echo "$GITHUB_EVENT_PATH"
      - run: |
          echo $GITHUB_EVENT_PATH
      - run: |
          echo "${{ env.GITHUB_EVENT_PATH }}"
      - run: |
          echo "${{ fromJSON(env.GITHUB_EVENT_PATH) }}"
