name: conditional workflow

on: pull_request

jobs:
  parent-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "parent-job is running"

  child-job:
    runs-on: ubuntu-latest
    if: ${{ jobs.parent-job.result == 'success'}}
    steps:
      - name: echo
        run: echo "child-job is running"
