name: experiments
on:
  - workflow_dispatch
  - push
jobs:
  experiments:
    name: Experiments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"
      - name: Set a multiline environment variable
        run: |
          echo "LIBRARIES_JSON<<EOF" >> "$GITHUB_ENV"
          echo $(cat ./libraries.json) >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      - name: Print multiline environment variable
        run: |
          echo "${{ env.LIBRARIES_JSON }}"

  print-details:
    needs: experiments
    runs-on: ubuntu-latest
    steps:
      - name: Print multiline environment variable
        run: |
          echo "${{ env.LIBRARIES_JSON }}"

#  build-libraries:
#    needs: experiments
#    name: Build libraries
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{fromJson(env.LIBRARIES_JSON)}}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Print details
#        run: |
#          echo ${{ matrix }}