name: Gradle build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gradle-build:
    name: Gradle build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        project: [demo, demo2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test ${{ matrix.project }}
        run: ./gradlew -p ${{ matrix.project }} test
      - name: Build ${{ matrix.project }}
        run: ./gradlew -p ${{ matrix.project }} build
