name: iteration
on:
  - pull_request
jobs:
  read-config:
    name: Read configuration
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare-change-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v36
        id: changed-files
      - uses: tj-actions/changed-files@v36
        id: changed-specific-files
        with:
          files_yaml: |
            demo: demo/**
            demo2: demo2/**
      - if: steps.changed-specific-files.outputs.demo_any_changed=='true'
        run: |
          echo "Directory demo has been changed"
      - id: prepare-change-matrix
        run: |
          echo "matrix=$(python3 ci/change_matrix.py libraries-python.json ${{ steps.changed-files.outputs.all_changed_files }})" >> $GITHUB_OUTPUT

  build:
    if: ${{ needs.read-config.outputs.matrix != '' }}
    needs: read-config
    name: Build library ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.read-config.outputs.matrix)}}
    steps:
      - name: Print library name
        run: |
          echo ${{ matrix.name }}

