name: iteration
on:
  - pull_request
jobs:
  read-config:
    name: Read configuration
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare-change-matrix.outputs.matrix }}
      changes-status: ${{ steps.prepare-change-status.outputs.change-status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v36
        id: changed-files
      - id: prepare-change-matrix
        run: |
          echo "matrix=$(python3 ci/change_matrix.py libraries-python.json ${{ steps.changed-files.outputs.all_changed_files }})" >> $GITHUB_OUTPUT
      - uses: tj-actions/changed-files@v36
        id: changed-specific-files
        with:
          files_yaml: |
            demo: demo/**
            demo2: demo2/**
      - run: |
          echo "${{toJSON(steps.changed-specific-files.outputs)}}"
#      - id: prepare-change-status
#        run: |
#          echo "change-status=${{ steps.changed-specific-files.outputs }}" >> $GITHUB_OUTPUT

#  echo:
#    needs: read-config
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print changes status
#        run: |
#          echo "${{toJSON(needs.read-config.outputs.changes-status)}}"
#      - name: Print demo changes
#        if: needs.read-config.outputs.changes-status.demo_any_changed == 'true'
#        run: |
#          echo "changes in demo folder happened"
#      - name: Print demo2 changes
#        if: needs.read-config.outputs.changes-status.demo2_any_changed == 'true'
#        run: |
#          echo "changes in demo2 folder happened"

  build:
    if: ${{ needs.read-config.outputs.matrix != '' }}
    needs: read-config
    name: Build library ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.read-config.outputs.matrix)}}
    steps:
      - name: Print library name
        run: |
          echo ${{ matrix.name }}

