name: iteration
on:
  - workflow_dispatch
jobs:
  read-config:
    name: Read configuration
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.read-json-step.outputs.LIBRARIES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read JSON file
        id: read-json-step
        run: |
          echo "LIBRARIES<<EOF" >> "$GITHUB_OUTPUT"
          echo $(cat ./libraries.json) >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  build:
    needs: read-config
    name: Build library ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.read-config.outputs.libraries)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          files: ${{ matrix.path }}
      - name: Change happened
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the ${{ matrix.path }} folder has changed."
