name: java infor

on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
          echo $JAVA_HOME
          java --version
          ls $JAVA_HOME/conf/security