name: on push
on: push
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          distribution: corretto
          java-version: 17.0.4
          cache: gradle
      - name: Print details
        run: |
          echo "---- java version"
          java --version
          echo "---- gradle version"
          gradle --version
          echo "---- aws version"
          aws --version
          echo "---- docker-compose version"
          docker-compose version
          echo "---- go version"
          go version
          echo "---- print ls"
          ls
