name: on push
on: push
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print details
        run: |
          echo "---- print pwd"
          pwd
          echo "---- print ls"
          ls
