name: on push
on: push
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: sdkman/sdkman-action@v1
        name: Install SDKMAN and Java
        with:
          candidate: java
          version: 17.0.4-amzn
      - name: Print details
        run: |
          echo "---- java version"
          java --version
          echo "---- sdk version"
          sdk version
          echo "---- aws version"
          aws --version
          echo "---- docker-compose version"
          docker-compose version
          echo "---- go version"
          go version
          echo "---- print ls"
          ls
