name: say hello - parent

on: pull_request

env:
  names: "[ 'Rafael', 'John', 'Jane' ]"

jobs:
  say-hello:
    strategy:
      matrix:
        name: ${{ fromJson(env.names) }}
    uses: ./.github/workflows/say-hello-child.yaml
    with:
      name: ${{ matrix.name }}
