name: say hello - parent

on: pull_request

env:
  names: "[ 'Rafael', 'John', 'Jane' ]"

jobs:
  env-vars:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ env.names }}
    steps:
      - run: echo "Add env vars to env-vars outputs"

  debug:
    needs: env-vars
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ fromJson(env.names) }}
      - run: echo ${{ fromJson(env.names).size }}
#      - run: echo ${{ needs.env-vars.names }}

#  say-hello:
#    needs: env-vars
#    strategy:
#      matrix:
#        name: ${{ fromJson(needs.env-vars.names) }}
#    uses: ./.github/workflows/say-hello-child.yaml
#    with:
#      name: ${{ matrix.name }}
